/*
 * <copyright>
 *  
 *  Copyright 2001-2004 BBNT Solutions, LLC
 *  under sponsorship of the Defense Advanced Research Projects
 *  Agency (DARPA).
 * 
 *  You can redistribute this software and/or modify it under the
 *  terms of the Cougaar Open Source License as published on the
 *  Cougaar Open Source Website (www.cougaar.org).
 * 
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *  
 * </copyright>
 */

package org.cougaar.core.service;

import org.cougaar.core.component.Service;
import org.cougaar.util.Trigger;
import org.cougaar.util.TriggerRegistry;

/**
 * This service is used to schedule plugins for thread execution. 
 * <p> 
 * The standard scheduler implementation just wraps the 
 * {@link ThreadService}.  An open enhancement request is to
 * port all SchedulerService clients to use the ThreadService
 * directly, making this service obsolete. 
 *
 * @see TriggerRegistry
 */
public interface SchedulerService extends Service, TriggerRegistry {

  /**
   * Register a client trigger, returning a "schedulerTrigger"
   * for the client to use.
   * <p>
   * <em>IMPORTANT:</em><br>
   * See the notes in <tt>TriggerRegistry.register(Trigger)</tt>
   * for threading issues.
   * @param clientTrigger the trigger to run when scheduled
   * @return a "schedulerTrigger" that the caller can use to tell 
   * the scheduler that it wants to be "clientTrigger.trigger()"ed.
   */
  Trigger register(Trigger clientTrigger);

  /**
   * Release a scheduler Trigger that was generated by 
   * <tt>register(..)</tt>.
   */
  void unregister(Trigger schedulerTrigger);
}

