/*
 * <copyright>
 *  
 *  Copyright 1997-2004 BBNT Solutions, LLC
 *  under sponsorship of the Defense Advanced Research Projects
 *  Agency (DARPA).
 * 
 *  You can redistribute this software and/or modify it under the
 *  terms of the Cougaar Open Source License as published on the
 *  Cougaar Open Source Website (www.cougaar.org).
 * 
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *  
 * </copyright>
 */

package org.cougaar.core.persist;

/**
 * Persistence constants.
 */
interface PersistenceNames {
  // Property name prefix
  final String PERSISTENCE_PROP_PREFIX = "org.cougaar.core.persistence.";

  // Simple names (plugin parameter names)
  final String PERSISTENCE_ARCHIVE_COUNT_NAME = "archiveCount";
  final String PERSISTENCE_CONSOLIDATION_PERIOD_NAME = "consolidationPeriod";
  final String PERSISTENCE_INTERVAL_NAME = "lazyInterval";
  final String PERSISTENCE_ENABLE_NAME = "enable";
  final String PERSISTENCE_DISABLE_WRITE_NAME = "disableWrite";
  final String PERSISTENCE_ARCHIVE_NUMBER_NAME = "archiveNumber";
  final String PERSISTENCE_CLASS_NAME = "class";
  final String PERSISTENCE_ROOT_NAME = "persistenceRoot";
  final String PERSISTENCE_DB_DRIVER_NAME = "driver";
  final String PERSISTENCE_DB_URL_NAME = "url";
  final String PERSISTENCE_DB_USER_NAME = "user";
  final String PERSISTENCE_DB_PASSWORD_NAME = "password";
  final String PERSISTENCE_DB_INTDEF_NAME = "intDef";
  final String PERSISTENCE_DB_LONGBINARYDEF_NAME = "longBinaryDef";
  final String PERSISTENCE_PARAMETERS_NAME = "parameters";
  final String[] NAMES = {
    PERSISTENCE_ARCHIVE_COUNT_NAME,
    PERSISTENCE_CONSOLIDATION_PERIOD_NAME,
    PERSISTENCE_INTERVAL_NAME,
    PERSISTENCE_ENABLE_NAME,
    PERSISTENCE_DISABLE_WRITE_NAME,
    PERSISTENCE_ARCHIVE_NUMBER_NAME,
    PERSISTENCE_CLASS_NAME,
    PERSISTENCE_ROOT_NAME,
    PERSISTENCE_DB_DRIVER_NAME,
    PERSISTENCE_DB_URL_NAME,
    PERSISTENCE_DB_USER_NAME,
    PERSISTENCE_DB_PASSWORD_NAME,
    PERSISTENCE_DB_INTDEF_NAME,
    PERSISTENCE_DB_LONGBINARYDEF_NAME,
    PERSISTENCE_PARAMETERS_NAME
  };    

  // Simple names with equal signs for "startsWith"
  final String PERSISTENCE_ARCHIVE_COUNT_PREFIX        = PERSISTENCE_ARCHIVE_COUNT_NAME        + "=";
  final String PERSISTENCE_CONSOLIDATION_PERIOD_PREFIX = PERSISTENCE_CONSOLIDATION_PERIOD_NAME + "=";
  final String PERSISTENCE_INTERVAL_PREFIX             = PERSISTENCE_INTERVAL_NAME             + "=";
  final String PERSISTENCE_ENABLE_PREFIX               = PERSISTENCE_ENABLE_NAME               + "=";
  final String PERSISTENCE_DISABLE_WRITE_PREFIX        = PERSISTENCE_DISABLE_WRITE_NAME        + "=";
  final String PERSISTENCE_ARCHIVE_NUMBER_PREFIX       = PERSISTENCE_ARCHIVE_NUMBER_NAME       + "=";
  final String PERSISTENCE_CLASS_PREFIX                = PERSISTENCE_CLASS_NAME                + "=";
  final String PERSISTENCE_ROOT_PREFIX                 = PERSISTENCE_ROOT_NAME                 + "=";
  final String PERSISTENCE_DB_DRIVER_PREFIX            = PERSISTENCE_DB_DRIVER_NAME            + "=";
  final String PERSISTENCE_DB_URL_PREFIX               = PERSISTENCE_DB_URL_NAME               + "=";
  final String PERSISTENCE_DB_USER_PREFIX              = PERSISTENCE_DB_USER_NAME              + "=";
  final String PERSISTENCE_DB_PASSWORD_PREFIX          = PERSISTENCE_DB_PASSWORD_NAME          + "=";
  final String PERSISTENCE_DB_INTDEF_PREFIX            = PERSISTENCE_DB_INTDEF_NAME            + "=";
  final String PERSISTENCE_DB_LONGBINARYDEF_PREFIX     = PERSISTENCE_DB_LONGBINARYDEF_NAME     + "=";
  final String PERSISTENCE_PARAMETERS_PREFIX           = PERSISTENCE_PARAMETERS_NAME           + "=";

  // Fully-qualified property names
  final String PERSISTENCE_ARCHIVE_COUNT_PROP        = PERSISTENCE_PROP_PREFIX + PERSISTENCE_ARCHIVE_COUNT_NAME;
  final String PERSISTENCE_CONSOLIDATION_PERIOD_PROP = PERSISTENCE_PROP_PREFIX + PERSISTENCE_CONSOLIDATION_PERIOD_NAME;
  final String PERSISTENCE_INTERVAL_PROP             = PERSISTENCE_PROP_PREFIX + PERSISTENCE_INTERVAL_NAME;
  final String PERSISTENCE_ENABLE_PROP               = PERSISTENCE_PROP_PREFIX + PERSISTENCE_ENABLE_NAME;
  final String PERSISTENCE_DISABLE_WRITE_PROP        = PERSISTENCE_PROP_PREFIX + PERSISTENCE_DISABLE_WRITE_NAME;
  final String PERSISTENCE_ARCHIVE_NUMBER_PROP       = PERSISTENCE_PROP_PREFIX + PERSISTENCE_ARCHIVE_NUMBER_NAME;
  final String PERSISTENCE_CLASS_PROP                = PERSISTENCE_PROP_PREFIX + PERSISTENCE_CLASS_NAME;
  final String PERSISTENCE_ROOT_PROP                 = PERSISTENCE_PROP_PREFIX + PERSISTENCE_ROOT_NAME;
  final String PERSISTENCE_DB_DRIVER_PROP            = PERSISTENCE_PROP_PREFIX + PERSISTENCE_DB_DRIVER_NAME;
  final String PERSISTENCE_DB_URL_PROP               = PERSISTENCE_PROP_PREFIX + PERSISTENCE_DB_URL_NAME;
  final String PERSISTENCE_DB_USER_PROP              = PERSISTENCE_PROP_PREFIX + PERSISTENCE_DB_USER_NAME;
  final String PERSISTENCE_DB_PASSWORD_PROP          = PERSISTENCE_PROP_PREFIX + PERSISTENCE_DB_PASSWORD_NAME;
  final String PERSISTENCE_DB_INTDEF_PROP            = PERSISTENCE_PROP_PREFIX + PERSISTENCE_DB_INTDEF_NAME;
  final String PERSISTENCE_DB_LONGBINARYDEF_PROP     = PERSISTENCE_PROP_PREFIX + PERSISTENCE_DB_LONGBINARYDEF_NAME;
  final String PERSISTENCE_PARAMETERS_PROP           = PERSISTENCE_PROP_PREFIX + PERSISTENCE_PARAMETERS_NAME;
}
